name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push to production repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: './docs'
          destination-github-username: 'ThatBlockyPenguin'
          destination-repository-name: 'Blog_Production'
          user-email: 41898282+github-actions[bot]@users.noreply.github.com
          target-branch: hosting
